### ISSUE TITLE
ClassNotFoundException at zeebe logs

### ISSUE THREAD

**Issue by spiner90** [camunda-community-hub/zeebe-hazelcast-exporter#184]
I watching some exceptions like this when start zeebe from image :
ghcr.io/camunda-community-hub/zeebe-with-hazelcast-exporter:1.3.6-1.1.1-SNAPSHOT
Its Ok?
Also some instances does not put to zeebe-simple-monitor.

```
 io.camunda.zeebe.util.jar.ExternalJarClassLoader - Failed to load class io.camunda.zeebe.util.jar.ExternalJarClassLoader, falling back to parent class loader
java.lang.ClassNotFoundException: io.camunda.zeebe.util.jar.ExternalJarClassLoader
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.jar.ExternalJarClassLoader.loadClass(ExternalJarClassLoader.java:54) ~[zeebe-util-1.3.6.jar:1.3.6]
	at org.apache.logging.log4j.core.impl.ThrowableProxyHelper.loadClass(ThrowableProxyHelper.java:205) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.impl.ThrowableProxyHelper.toExtendedStackTrace(ThrowableProxyHelper.java:112) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:112) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:96) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.impl.Log4jLogEvent.getThrownProxy(Log4jLogEvent.java:629) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:63) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:44) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternFormatterPatternSerializer.toSerializable(PatternLayout.java:385) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:241) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:226) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:60) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:197) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:190) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:181) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:312) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:533) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.Logger.log(Logger.java:161) ~[log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2040) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1907) ~[log4j-api-2.17.1.jar:2.17.1]
	at org.apache.logging.slf4j.Log4jLogger.trace(Log4jLogger.java:69) ~[log4j-slf4j-impl-2.17.1.jar:2.17.1]
	at io.camunda.zeebe.util.jar.ExternalJarClassLoader.loadClass(ExternalJarClassLoader.java:56) ~[zeebe-util-1.3.6.jar:1.3.6]
	at io.zeebe.exporter.proto.RecordTransformer.toProcessInstanceRecord(RecordTransformer.java:391) ~[zeebe-hazelcast-exporter-jar-with-dependencies.jar:1.1.1-SNAPSHOT]
	at io.zeebe.exporter.proto.RecordTransformer.toProtobufMessage(RecordTransformer.java:146) ~[zeebe-hazelcast-exporter-jar-with-dependencies.jar:1.1.1-SNAPSHOT]
	at io.zeebe.exporter.proto.RecordTransformer.toGenericRecord(RecordTransformer.java:157) ~[zeebe-hazelcast-exporter-jar-with-dependencies.jar:1.1.1-SNAPSHOT]
	at io.zeebe.hazelcast.exporter.HazelcastExporter.recordToProtobuf(HazelcastExporter.java:160) ~[zeebe-hazelcast-exporter-jar-with-dependencies.jar:1.1.1-SNAPSHOT]
	at io.zeebe.hazelcast.exporter.HazelcastExporter.export(HazelcastExporter.java:147) ~[zeebe-hazelcast-exporter-jar-with-dependencies.jar:1.1.1-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$export$3(ExporterContainer.java:156) ~[zeebe-broker-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader(ThreadContextUtil.java:58) ~[zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader(ThreadContextUtil.java:34) ~[zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.export(ExporterContainer.java:155) ~[zeebe-broker-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.exportRecord(ExporterContainer.java:142) ~[zeebe-broker-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector$RecordExporter.export(ExporterDirector.java:510) ~[zeebe-broker-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) [zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) [zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) [zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) [zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) [zeebe-util-1.3.6.jar:1.3.6]
```

**Comment by saig0** [comment]
@spiner90 thank you for reporting. I can't reproduce the issue. The Docker image is working fine for me. 

What do you try to achieve?

**Comment by saig0** [comment]
I'm closing this issue because of inactivity. Feel free to reopen if the issue is still relevant.
