### ISSUE TITLE
I can define the cluster name of a remote Hazelcast cluster

### ISSUE THREAD

**Issue by kilinochi** [camunda-community-hub/zeebe-hazelcast-exporter#98]
Hey! I am trying connect to cluster to another machine (dev1), my hazelcast.xml look like this 

```
<hazelcast xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.hazelcast.com/schema/config
        http://www.hazelcast.com/schema/config/hazelcast-config-4.1.xsd"
        xmlns="http://www.hazelcast.com/schema/config">
          <cluster-name>mobile-zeebe</cluster-name>
          <network> 
                 <public-address>dev1</public-address>
                  <port auto-increment="false">5071</port>
                  <join>
	            <multicast enabled="false"></multicast>
                 </join>
        </network>
</hazelcast>
```

And I have next exporter config
```
zeebe:
  broker:
    exporters:
      hazelcast:
        className: io.zeebe.hazelcast.exporter.HazelcastExporter
        jarPath: exporters/zeebe-hazelcast-exporter.jar
	args:
    	  port: 5701
          enabledValueTypes: ""
          enabledRecordTypes:  ""
          name: "zeebe-mobile"
          capacity: 10000 
          timeToLiveInSeconds: 0
          format = "json"
          remoteAddress: dev1
```

And I have next error

```
Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
        at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.authenticateOnCluster(ClientConnectionManagerImpl.java:792) ~[zeebe-hazelcast-exporter-0.10.0.jar:0.10.0]
        at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:580) ~[zeebe-hazelcast-exporter-0.10.0.jar:0.10.0]
        at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.connect(ClientConnectionManagerImpl.java:423) ~[zeebe-hazelcast-exporter-0.10.0.jar:0.10.0]
        at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.doConnectToCandidateCluster(ClientConnectionManagerImpl.java:451) ~[zeebe-hazelcast-exporter-0.10.0.jar:0.10.0]
        at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.doConnectToCluster(ClientConnectionManagerImpl.java:385) ~[zeebe-hazelcast-exporter-0.10.0.jar:0.10.0]
        at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.connectToCluster(ClientConnectionManagerImpl.java:346) ~[zeebe-hazelcast-exporter-0.10.0.jar:0.10.0]
        at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.start(ClientConnectionManagerImpl.java:296) ~[zeebe-hazelcast-exporter-0.10.0.jar:0.10.0]
        at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:363) ~[zeebe-hazelcast-exporter-0.10.0.jar:0.10.0]
        at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460) ~[zeebe-hazelcast-exporter-0.10.0.jar:0.10.0]
        at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416) ~[zeebe-hazelcast-exporter-0.10.0.jar:0.10.0]
        at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:136) ~[zeebe-hazelcast-exporter-0.10.0.jar:0.10.0]
        at io.zeebe.hazelcast.exporter.HazelcastExporter.connectToHazelcast(HazelcastExporter.java:118) ~[zeebe-hazelcast-exporter-0.10.0.jar:0.10.0]
        at java.util.Optional.map(Unknown Source) ~[?:?]
        at io.zeebe.hazelcast.exporter.HazelcastExporter.open(HazelcastExporter.java:67) ~[zeebe-hazelcast-exporter-0.10.0.jar:0.10.0]
        at io.zeebe.broker.exporter.stream.ExporterContainer.openExporter(ExporterContainer.java:64) ~[zeebe-broker-0.26.0.jar:0.26.0]
        at io.zeebe.broker.exporter.stream.ExporterDirector.onSnapshotRecovered(ExporterDirector.java:240) ~[zeebe-broker-0.26.0.jar:0.26.0]
        at io.zeebe.broker.exporter.stream.ExporterDirector.onActorStarted(ExporterDirector.java:164) ~[zeebe-broker-0.26.0.jar:0.26.0]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.26.0.jar:0.26.0]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.0.jar:0.26.0]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.0.jar:0.26.0]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.0.jar:0.26.0]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.0.jar:0.26.0]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.0.jar:0.26.0]
```

How I can set cluster name to exporter?

**Comment by saig0** [comment]
Currently, it is not possible to set the cluster name. To connect the exporter to an external Hazelcast cluster, you can only specify the `remoteAddress`.

Feel free to contribute and add this feature :)

**Comment by saig0** [comment]
To sum it up, we want to extend the configuration of the exporter by `remoteClusterName`. The exporter uses the `name` as the cluster name when connecting to a remote Hazelcast instance.
